from __future__ import annotations

from pathlib import Path

from mi300x_launch_doctor.intake.inventory import read_text
from mi300x_launch_doctor.schemas import GeneratedFile


CUDA_SPECIFIC_PACKAGES = {
    "bitsandbytes": "Validate ROCm quantization support or replace backend.",
    "flash-attn": "Validate ROCm-compatible attention kernels or use container-supported kernels.",
    "cupy-cuda": "Replace with a ROCm-compatible CuPy package or remove CUDA-specific CuPy.",
    "tensorflow-gpu": "Use a current ROCm-validated TensorFlow path or prefer PyTorch ROCm.",
}


def generate_requirements(root: Path, files: list[Path]) -> GeneratedFile:
    requirement_file = first_dependency_file(root, files)
    if requirement_file:
        content = transform_requirements(read_text(requirement_file))
    else:
        content = default_requirements()
    return GeneratedFile(name="requirements-rocm.txt", path="generated/requirements-rocm.txt", content=content)


def first_dependency_file(root: Path, files: list[Path]) -> Path | None:
    preferred = ["requirements.txt", "requirements-dev.txt"]
    by_name = {path.name.lower(): path for path in files}
    for name in preferred:
        if name in by_name:
            return by_name[name]
    return None


def transform_requirements(text: str) -> str:
    output = [
        "# Generated by MI300X Launch Doctor.",
        "# CUDA-specific packages are commented with ROCm migration notes.",
        "",
    ]
    for raw_line in text.splitlines():
        line = raw_line.strip()
        lowered = line.lower()
        package_key = next((pkg for pkg in CUDA_SPECIFIC_PACKAGES if lowered.startswith(pkg)), None)
        if not line or line.startswith("#"):
            output.append(raw_line)
        elif package_key:
            output.append(f"# {raw_line}")
            output.append(f"# ROCm note: {CUDA_SPECIFIC_PACKAGES[package_key]}")
        else:
            output.append(raw_line)
    if "torch" not in text.lower():
        output.extend(["", "# PyTorch ROCm is provided by the rocm/pytorch Docker base image."])
    return "\n".join(output).rstrip() + "\n"


def default_requirements() -> str:
    return """# Generated by MI300X Launch Doctor.
# PyTorch ROCm is provided by the rocm/pytorch Docker base image.
transformers
accelerate
vllm
"""
